name: Deploy to Render
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  on-success:
    runs-on: ubuntu-latest
    steps:
      - name: Print success message
        run: echo "Deployment successful!"
  deploy:
    if: ${{ github.event_name == 'push' }}
    name: Wait for Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Render Deployment
        uses: bounceapp/render-action@0.6.0
        with:
          render-token: ${{ secrets.RENDER_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          service-id: srv-cg4nhi02qv287cq05a90
          retries: 20
          wait: 16000
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Abruptly end the workflow
        run: exit 1
