name: Test, Build, and Deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      run: npm test

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: my-test-app
      IMAGE_TAG: latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
        build-args: |
          NODE_VERSION=${{ matrix.node-version }}

  create-pull-request:
    needs: build-and-deploy
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SOURCE_BRANCH: main
      TARGET_BRANCH: master

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ env.SOURCE_BRANCH }}

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        branch: ${{ env.SOURCE_BRANCH }}
        base: ${{ env.TARGET_BRANCH }}
        title: "Deploy latest changes"
        body: "Automatically deployed the latest changes using GitHub Actions."
        commit-message: "Deploy latest changes"

  merge-to-master:
    needs: create-pull-request
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Merge pull request to master
      uses: peter-evans/merge-pull-request@v1.0.1
      with:
        github-token: ${{ env.GITHUB_TOKEN }}
        pull-request-number: ${{ github.event.pull_request.number }}
        merge-method: squash
