name: Test, Build, and Deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      run: npm test

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: my-test-app
      IMAGE_TAG: latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
        build-args: |
          NODE_VERSION=${{ matrix.node-version }}

  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: 'Merge main to master'
          head: main
          base: master
          body: |
            **Changes:**
            - ${{ github.event.head_commit.message }}
            **Deploy Notes:**
            N/A
            **Post Deploy Test Instructions:**
            1. Do this
            2. Do that

  merge-to-master:
    runs-on: ubuntu-latest
    needs: create-pr
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: 'master'
      - name: Merge branch
        uses: peter-evans/merge-pull-request@v1
        with:
          pull-number: ${{ github.event.pull_request.number }}
          merge-method: 'squash'
        env:
          GITHUB_TOKEN: ${{ secrets.HUB_TOKEN }}