name: Glitch Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Glitch
        uses: jakejarvis/glitch-deploy@v4
        with:
          args: |
            --token=${{ secrets.GLITCH_TOKEN }}
            --repo=${{ secrets.GLITCH_REPO }}
            --branch=main
