name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/my-test-app:latest

      - name: Wait for Render Deployment
        uses: renderapp/deploy-action@1.7.1
        with:
          render-token: ${{ secrets.RENDER_TOKEN }}
          github-token: ${{ secrets.HUB_TOKEN }}
          service-id: srv-cg4nhi02qv287cq05a90
          render_yaml: render.yaml
          retries: 20
          wait: 16000
          sleep: 30000